package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.githubAppConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            githubAppConnection {
                id = "PROJECT_EXT_30"
                displayName = "appMoiseev"
                appId = "381000"
                clientId = "Iv1.4e9bf005b09c0efb"
                clientSecret = "credentialsJSON:2c460a70-94ef-402b-b926-5f69b8ec40fd"
                privateKey = "credentialsJSON:1899b9cb-c8b2-4f76-af84-4d25089ec1e1"
                ownerUrl = "https://github.com/dumamoiseev"
            }
        }
    }
}
